# Generated by Django 4.1.7 on 2023-07-23 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StorManager', '0007_alter_packageitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('numItems', models.IntegerField(default=0)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('createDate', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('DateSelect', models.DateTimeField()),
                ('ItemType', models.CharField(default='default', max_length=20)),
                ('PartOrFull', models.CharField(default='FullPackage', max_length=20)),
                ('OrderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageOrder.order')),
                ('itemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StorManager.item')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItemOrder',
            fields=[
                ('PackageItemOrderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OrderItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageOrder.orderitem')),
                ('PackageItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StorManager.packageitem')),
            ],
        ),
    ]
