# Generated by Django 4.1.7 on 2023-07-25 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageOrder', '0002_alter_orderitem_dateselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='DateSelect',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 11, 52, 47, 71538)),
        ),
    ]
