# Generated by Django 4.1.7 on 2023-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorManager', '0002_item_itemdescription_alter_item_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemVisual',
            field=models.FileField(upload_to='StorManager/itemImages'),
        ),
    ]
