# Generated by Django 4.1.7 on 2023-07-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorManager', '0003_alter_item_itemvisual'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemType',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('PackageItemId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PackageItemName', models.CharField(max_length=60)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StorManager.item')),
            ],
        ),
    ]
