# Generated by Django 4.1.7 on 2023-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorManager', '0004_item_itemtype_alter_item_price_packageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitem',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
