# Generated by Django 4.1.7 on 2023-07-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorManager', '0005_packageitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='Price',
            field=models.FloatField(default=0.0),
        ),
    ]
