# Generated by Django 4.1.7 on 2023-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorManager', '0006_alter_packageitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
